### PR TITLE
Adding a more Kirby-like look to it

### PR DESCRIPTION
**Pull request by xu-chris**

### CODE REVIEW

**Comment by xu-chris** [comment]
bildschirmfoto 2016-01-03 um 15 23 48

**Comment by Jayshua** [comment]
I'm not sure about using em to size the arrow. That isn't really something that should change with the text size, don't you think?

**Comment by xu-chris** [comment]
Honestly I've just copied the code from `panel/assets/css/panel.css` to get the Kirby look.

**Comment by Jayshua** [comment]
Ok, I'll just switch that to pixels. Thanks for the help!

**Pull request merged**
